version: '3.9'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passw0rd
    volumes: 
      - miaoyudian-db:/data/db

volumes:
  miaoyudian-db:
