version: '3.9'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - .env.mongodb
    volumes: 
      - miaoyudian-db:/data/db
  
  forum-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10127:10127"
    restart: always
    depends_on:
      - mongodb

volumes:
  miaoyudian-db:
    driver: local
